apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magma
  namespace: argocd
spec:
  project: default
  source:
    path: charts
    repoURL: https://github.com/nitinrajput1997/magma-charts-2-3-2022-v2
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: orc8r
